spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: validate

app:
  database-access-type: jdbc
