services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=username'
    ports:
      - '5432:5432'
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25.0
    depends_on:
      - postgres
    command:
      - --hub-mode=off
      - --changelog-file=./src/main/resources/db/changelog/db.changelog-master.yaml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://localhost:5432/postgres
      - --username=username
      - --password=password
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

networks:
  backend: { }
